config/routes.rb
Rails.application.routes.draw do
  resources :order_items
  resources :orders
  resources :products
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
  get 'home/index'
  resources :home
  root to: 'home#index'
end

app/models/order.rb
class Order < ApplicationRecord
  enum status: { draft: 0, placed: 1, payment_confirmed: 2, preparing: 3, prepared: 4, delivered: 5 }
  has_many :order_items
  has_many :products, through: :order_items
  belongs_to :user
  accepts_nested_attributes_for :order_items, allow_destroy: true, reject_if: proc { |oi| oi[:quantity] == '0' }
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  def index
    @orders = Order.all
  end

  def new
    @order = Order.new
    render layout: false
  end

  def create
    @order = Order.new(order_params)
    if @order.save
      redirect_to orders_url, notice: 'Order was successfully created.'
    else
      render_failure(@order)
    end
  end

  def edit
    render layout: false
  end

  def update
    if @order.update(order_params)
      redirect_to orders_url, notice: 'Order was successfully updated.'
    else
      render_failure(@order)
    end
  end

  def show
    render layout: false
  end

  def destroy
    @order.destroy
    redirect_to orders_url, notice: 'Order was successfully destroyed.'
  end

  private
    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:user_id, :payment_mode, :status, :total, order_items_attributes: [:product_id, :quantity])
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.haml
= form_with(model: object, remote: true) do |f|
  - if object.errors.any?
    #error_explanation
      %p= "#{pluralize(object.errors.count, "error")} prohibited this Order from being saved:"
      %ul
        - object.errors.full_messages.each do |message|
          %li= message
  .row
    = f.label :user_id
    = f.collection_select :user_id, User.all, :id, :name
  .row
    = f.label :payment_mode
    = f.number_field :payment_mode
  .row
    = f.label :status
    = f.collection_select :status, Order.statuses, :first, :first
  .row
    = f.label :total
    = f.text_field :total
  = render 'shared/timestamps', f: f # TODO: Add this partial to generator
  = render 'shared/reveal_footer', f: f # TODO: Add this partial to generator

app/views/orders/edit.html.haml
%h1= "Editing Order: ##{@order.id}"

= render 'form', object: @order

app/views/orders/index.html.haml
%h1
  Orders
  = link_to 'Add New Order', 'javascript:void(0)', class: 'button primary float-right', data: {open: 'ajax-reveal', url: new_order_path}

.table-scroll
  %table.striped.hover.table-striped.stack
    %thead
      %tr
        %th Id
        %th User
        %th Payment mode
        %th Status
        %th Total
        %th Actions

    %tbody
      - @orders.each do |order|
        %tr
          %td= order.id
          %td= order.user.name
          %td= order.payment_mode
          %td= order.status
          %td= order.total
          %td
            .button-group
              = link_to 'Show', 'javascript:void(0)', class: 'button success', data: {open: 'ajax-reveal', url: order_path(order)}
              = link_to 'Edit', 'javascript:void(0)', class: 'button warning', data: {open: 'ajax-reveal', url: edit_order_path(order)}
              = link_to 'Delete', order, method: :delete, data: { confirm: 'Are you sure you want to delete this Order?' }, class: 'button alert'

app/views/orders/new.html.haml
%h1 New Order

= render 'form', object: @order

app/views/orders/show.html.haml
.row
  %strong Id:
  = @order.id
.row
  %strong User:
  = @order.user.name
.row
  %strong Payment mode:
  = @order.payment_mode
.row
  %strong Status:
  = @order.status
.row
  %strong Total:
  = @order.total
.row
  = link_to 'Edit', 'javascript:void(0)', class: 'button primary', data: {open: 'ajax-reveal', url: edit_order_path(@order)}
  = close_reveal_button # TODO: Add this method to be copied via generator