config/routes.rb
Rails.application.routes.draw do
  resources :order_items
  resources :orders
  resources :products
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
  get 'home/index'
  resources :home
  root to: 'home#index'
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  before_action :set_order_item, only: [:show, :edit, :update, :destroy]

  def index
    @order_items = OrderItem.all
  end

  def new
    @order_item = OrderItem.new
    render layout: false
  end

  def create
    @order_item = OrderItem.new(order_item_params)
    if @order_item.save
      redirect_to order_items_url, notice: 'Order item was successfully created.'
    else
      render_failure(@order_item)
    end
  end

  def edit
    render layout: false
  end

  def update
    if @order_item.update(order_item_params)
      redirect_to order_items_url, notice: 'Order item was successfully updated.'
    else
      render_failure(@order_item)
    end
  end

  def show
    render layout: false
  end

  def destroy
    @order_item.destroy
    redirect_to order_items_url, notice: 'Order item was successfully destroyed.'
  end

  private
    def set_order_item
      @order_item = OrderItem.find(params[:id])
    end

    def order_item_params
      params.require(:order_item).permit(:order_id, :product_id, :quantity)
    end
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/views/order_items/_form.html.haml
= form_with(model: object, remote: true) do |f|
  - if object.errors.any?
    #error_explanation
      %p= "#{pluralize(object.errors.count, "error")} prohibited this Order Item from being saved:"
      %ul
        - object.errors.full_messages.each do |message|
          %li= message
  .row
    = f.label :order_id
    = f.collection_select :order_id, Order.all, :id, :id
  .row
    = f.label :product_id
    = f.collection_select :product_id, Product.all, :id, :name
  .row
    = f.label :quantity
    = f.number_field :quantity
  = render 'shared/timestamps', f: f # TODO: Add this partial to generator
  = render 'shared/reveal_footer', f: f # TODO: Add this partial to generator

app/views/order_items/edit.html.haml
%h1= "Editing Order Item: ##{@order_item.id}"

= render 'form', object: @order_item

app/views/order_items/index.html.haml
%h1
  Order Items
  = link_to 'Add New Order Item', 'javascript:void(0)', class: 'button primary float-right', data: {open: 'ajax-reveal', url: new_order_item_path}

.table-scroll
  %table.striped.hover.table-striped.stack
    %thead
      %tr
        %th Id
        %th Order
        %th Product
        %th Quantity
        %th Actions

    %tbody
      - @order_items.each do |order_item|
        %tr
          %td= order_item.id
          %td= order_item.order.id
          %td= order_item.product.name
          %td= order_item.quantity
          %td
            .button-group
              = link_to 'Show', 'javascript:void(0)', class: 'button success', data: {open: 'ajax-reveal', url: order_item_path(order_item)}
              = link_to 'Edit', 'javascript:void(0)', class: 'button warning', data: {open: 'ajax-reveal', url: edit_order_item_path(order_item)}
              = link_to 'Delete', order_item, method: :delete, data: { confirm: 'Are you sure you want to delete this Order Item?' }, class: 'button alert'

app/views/order_items/new.html.haml
%h1 New Order Item

= render 'form', object: @order_item

app/views/order_items/show.html.haml
.row
  %strong Id:
  = @order_item.id
.row
  %strong Order:
  = @order_item.order.id
.row
  %strong Product:
  = @order_item.product.name
.row
  %strong Quantity:
  = @order_item.quantity
.row
  = link_to 'Edit', 'javascript:void(0)', class: 'button primary', data: {open: 'ajax-reveal', url: edit_order_item_path(@order_item)}
  = close_reveal_button # TODO: Add this method to be copied via generator